name: Publish website

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build with Hugo
      run: hugo --minify

    - name: Deploy through FTP
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        local-dir: public/
        ftp-server: sftp://asmi.ro/caravana/
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure
